package com.students.students.model;

public enum Department {
    SOFTWARE_ENGINEERING, MATERIALS_ENGINEERING, ELECTRONICS_ENGINEERING,
    COMPUTER_SCIENCE, ECONOMICS, BIOLOGY, DATA_ENGINEERING, CHEMISTRY,
    PHYSICS, EDUCATION, PSYCHOLOGY
}
